#!/bin/sh
# Run the frontend development server

set -e

cd "$(dirname "$0")/.."

if [ ! -d "./node_modules" ]; then
    echo "Directory /node_modules DOES NOT exists."
    echo "Running script/bootstrap"
    ./script/bootstrap
fi

./node_modules/.bin/gulp develop-velbus
