// Tasks to run rspack.

import log from "fancy-log";
import fs from "fs";
import gulp from "gulp";
import rspack from "@rspack/core";
import paths from "../paths.cjs";
import { createVelbusConfig } from "../rspack.cjs";

const isWsl =
  fs.existsSync("/proc/version") &&
  fs.readFileSync("/proc/version", "utf-8").toLocaleLowerCase().includes("microsoft");

gulp.task("ensure-velbus-build-dir", (done) => {
  if (!fs.existsSync(paths.velbus_output_root)) {
    fs.mkdirSync(paths.velbus_output_root, { recursive: true });
  }
  done();
});

gulp.task("set-dev-flag", (done) => {
  fs.writeFileSync(
    `${paths.velbus_dir}/velbus_frontend/constants.py`,
    '"""Generated by the development frontend build."""\n\nIS_PROD_BUILD = False\n',
  );
  done();
});

gulp.task("set-prod-flag", (done) => {
  fs.writeFileSync(
    `${paths.velbus_dir}/velbus_frontend/constants.py`,
    '"""Generated by the production frontend build."""\n\nIS_PROD_BUILD = True\n',
  );
  done();
});

const doneHandler = (done) => (err, stats) => {
  if (err) {
    log.error(err.stack || err);
    if (err.details) {
      log.error(err.details);
    }
    return;
  }

  if (stats.hasErrors() || stats.hasWarnings()) {
    console.log(stats.toString("minimal"));
  }

  log(`Build done @ ${new Date().toLocaleTimeString()}`);

  if (done) {
    done();
  }
};

const prodBuild = (conf) =>
  new Promise((resolve) => {
    rspack(
      conf,
      doneHandler(resolve),
    );
  });

gulp.task("rspack-watch-velbus", () => {
  rspack(
    createVelbusConfig({
      isProdBuild: false,
      latestBuild: true,
    }),
  ).watch({ ignored: /build/, poll: isWsl }, doneHandler());
});

gulp.task("rspack-prod-velbus", () =>
  prodBuild(
    createVelbusConfig({
      isProdBuild: true,
      latestBuild: true,
    }),
  ),
);
